import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {OrbitControls} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js';

const $=s=>document.querySelector(s), sceneEl=$('#scene'), logEl=$('#log'), turnEl=$('#turn'), stateEl=$('#state');
const scene=new THREE.Scene(); scene.fog=new THREE.Fog(0x071019,15,32);
const camera=new THREE.PerspectiveCamera(42,1,.1,100); camera.position.set(8.5,10.5,9.5);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; sceneEl.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement); controls.enableDamping=true; controls.target.set(0,0,0); controls.minDistance=7;controls.maxDistance=22;controls.maxPolarAngle=1.45;
scene.add(new THREE.HemisphereLight(0xcceeff,0x17202a,2.1)); const sun=new THREE.DirectionalLight(0xffffff,3.2);sun.position.set(6,12,5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
const boardGroup=new THREE.Group(),pieceGroup=new THREE.Group(),fxGroup=new THREE.Group();scene.add(boardGroup,pieceGroup,fxGroup);
const themes={classic:{light:0xd7c7a3,dark:0x4b3425,w:0xf4eee2,b:0x232831,glow:0xfbbf24},arcane:{light:0x28465d,dark:0x111c3c,w:0x7dd3fc,b:0xa78bfa,glow:0x67e8f9},monsters:{light:0x536b43,dark:0x253422,w:0xc7f9a9,b:0x7b3248,glow:0xb7ff62},brick:{light:0xb8b8aa,dark:0x39465a,w:0xe5e7eb,b:0xdc3d3d,glow:0xfbbf24},cosmic:{light:0x273552,dark:0x090b20,w:0x8be9fd,b:0xff79c6,glow:0x5eead4}};
let theme='classic',board=[],turn='w',selected=null,legal=[],history=[],ep=null,castling={w:{k:true,q:true},b:{k:true,q:true}},busy=false,soundOn=true,aiTimer=null;
const back=['r','n','b','q','k','b','n','r']; const symbols={k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'};
function reset(){board=Array.from({length:8},()=>Array(8).fill(null));for(let x=0;x<8;x++){board[0][x]={c:'b',t:back[x]};board[1][x]={c:'b',t:'p'};board[6][x]={c:'w',t:'p'};board[7][x]={c:'w',t:back[x]}}turn='w';selected=null;legal=[];history=[];ep=null;castling={w:{k:true,q:true},b:{k:true,q:true}};logEl.innerHTML='';buildPieces();refresh();stateEl.textContent='Battle ready'}
function buildBoard(){boardGroup.clear();const base=new THREE.Mesh(new THREE.BoxGeometry(9,.35,9),new THREE.MeshStandardMaterial({color:0x101820,roughness:.55,metalness:.35}));base.position.y=-.25;base.receiveShadow=true;boardGroup.add(base);for(let z=0;z<8;z++)for(let x=0;x<8;x++){const sq=new THREE.Mesh(new THREE.BoxGeometry(.98,.12,.98),new THREE.MeshStandardMaterial({color:((x+z)%2?themes[theme].dark:themes[theme].light),roughness:.7,metalness:.05,emissive:0x000000}));sq.position.set(x-3.5,0,z-3.5);sq.userData={square:true,x,z};sq.receiveShadow=true;boardGroup.add(sq)}}
function mat(color,em=0){return new THREE.MeshStandardMaterial({color,roughness:.38,metalness:theme==='cosmic'?.65:.18,emissive:em,emissiveIntensity:.4})}
function pieceMesh(p,x,z){const g=new THREE.Group(),color=p.c==='w'?themes[theme].w:themes[theme].b,m=mat(color); const add=(geo,y,s=1)=>{const q=new THREE.Mesh(geo,m);q.position.y=y;q.scale.setScalar(s);q.castShadow=true;q.receiveShadow=true;g.add(q)};
 add(new THREE.CylinderGeometry(.36,.46,.18,theme==='brick'?8:24),.12);add(new THREE.CylinderGeometry(.27,.34,.16,theme==='brick'?8:24),.28);
 const bodyH=p.t==='p'?.5:p.t==='k'?1.0:.78;add(new THREE.CylinderGeometry(.16,.29,bodyH,theme==='brick'?8:20),.36+bodyH/2);
 if(p.t==='p')add(new THREE.SphereGeometry(.23,theme==='brick'?8:20,theme==='brick'?6:14),.92);
 if(p.t==='r'){add(new THREE.CylinderGeometry(.31,.24,.34,theme==='brick'?8:16),1.02);for(let i=0;i<4;i++){const b=new THREE.Mesh(new THREE.BoxGeometry(.15,.16,.15),m);b.position.set(Math.cos(i*Math.PI/2)*.23,1.23,Math.sin(i*Math.PI/2)*.23);g.add(b)}}
 if(p.t==='n'){add(new THREE.ConeGeometry(.3,.62,theme==='brick'?5:12),1.08);g.rotation.y=p.c==='w'?0:Math.PI}
 if(p.t==='b'){add(new THREE.SphereGeometry(.27,theme==='brick'?8:18,theme==='brick'?6:12),1.1);add(new THREE.ConeGeometry(.16,.35,theme==='brick'?6:16),1.38)}
 if(p.t==='q'){add(new THREE.SphereGeometry(.29,theme==='brick'?8:20,theme==='brick'?6:12),1.22);for(let i=0;i<5;i++){const b=new THREE.Mesh(new THREE.SphereGeometry(.08,8,6),m);b.position.set(Math.cos(i*1.256)*.26,1.5,Math.sin(i*1.256)*.26);g.add(b)}}
 if(p.t==='k'){add(new THREE.SphereGeometry(.28,theme==='brick'?8:20,theme==='brick'?6:12),1.38);const v=new THREE.Mesh(new THREE.BoxGeometry(.12,.45,.12),m);v.position.y=1.72;g.add(v);const h=new THREE.Mesh(new THREE.BoxGeometry(.38,.11,.11),m);h.position.y=1.77;g.add(h)}
 if(theme==='monsters'){const horn=mat(p.c==='w'?0xd9f99d:0xfda4af);[-1,1].forEach(s=>{const q=new THREE.Mesh(new THREE.ConeGeometry(.07,.3,8),horn);q.position.set(.18*s,1.1,.05);q.rotation.z=-s*.35;g.add(q)})}
 if(theme==='arcane'||theme==='cosmic'){const ring=new THREE.Mesh(new THREE.TorusGeometry(.34,.025,8,32),mat(themes[theme].glow,themes[theme].glow));ring.rotation.x=Math.PI/2;ring.position.y=.48;g.add(ring)}
 g.position.set(x-3.5,.08,z-3.5);g.userData={piece:true,x,z};g.traverse(o=>o.userData.root=g);return g}
function buildPieces(){pieceGroup.clear();for(let z=0;z<8;z++)for(let x=0;x<8;x++)if(board[z][x])pieceGroup.add(pieceMesh(board[z][x],x,z));highlight()}
function inBounds(x,z){return x>=0&&x<8&&z>=0&&z<8} const opp=c=>c==='w'?'b':'w';
function pseudo(b,x,z,attacks=false){const p=b[z][x];if(!p)return[];const out=[],push=(nx,nz)=>{if(inBounds(nx,nz)&&(!b[nz][nx]||b[nz][nx].c!==p.c))out.push([nx,nz])};const ray=(dx,dz)=>{let nx=x+dx,nz=z+dz;while(inBounds(nx,nz)){if(!b[nz][nx])out.push([nx,nz]);else{if(b[nz][nx].c!==p.c)out.push([nx,nz]);break}nx+=dx;nz+=dz}};
 if(p.t==='p'){const d=p.c==='w'?-1:1;if(attacks){for(const dx of[-1,1])if(inBounds(x+dx,z+d))out.push([x+dx,z+d])}else{if(inBounds(x,z+d)&&!b[z+d][x]){out.push([x,z+d]);const start=p.c==='w'?6:1;if(z===start&&!b[z+2*d][x])out.push([x,z+2*d])}for(const dx of[-1,1])if(inBounds(x+dx,z+d)&&(b[z+d][x+dx]?.c===opp(p.c)||(ep&&ep.x===x+dx&&ep.z===z+d)))out.push([x+dx,z+d])}}
 if(p.t==='n')for(const[dX,dZ]of[[1,2],[2,1],[-1,2],[-2,1],[1,-2],[2,-1],[-1,-2],[-2,-1]])push(x+dX,z+dZ);
 if('brq'.includes(p.t)){const dirs=[];if('bq'.includes(p.t))dirs.push([1,1],[-1,1],[1,-1],[-1,-1]);if('rq'.includes(p.t))dirs.push([1,0],[-1,0],[0,1],[0,-1]);dirs.forEach(d=>ray(...d))}
 if(p.t==='k'){for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++)if(dx||dz)push(x+dx,z+dz);if(!attacks){const row=p.c==='w'?7:0;if(z===row&&x===4&&!isCheck(b,p.c)){if(castling[p.c].k&&!b[row][5]&&!b[row][6]&&b[row][7]?.t==='r'&&!attacked(b,5,row,opp(p.c))&&!attacked(b,6,row,opp(p.c)))out.push([6,row]);if(castling[p.c].q&&!b[row][1]&&!b[row][2]&&!b[row][3]&&b[row][0]?.t==='r'&&!attacked(b,3,row,opp(p.c))&&!attacked(b,2,row,opp(p.c)))out.push([2,row])}}}return out}
function attacked(b,x,z,by){for(let zz=0;zz<8;zz++)for(let xx=0;xx<8;xx++)if(b[zz][xx]?.c===by&&pseudo(b,xx,zz,true).some(m=>m[0]===x&&m[1]===z))return true;return false}
function isCheck(b,c){for(let z=0;z<8;z++)for(let x=0;x<8;x++)if(b[z][x]?.c===c&&b[z][x].t==='k')return attacked(b,x,z,opp(c));return true}
function clone(b){return b.map(r=>r.map(p=>p?{...p}:null))}
function legalMoves(x,z){const p=board[z][x];if(!p)return[];return pseudo(board,x,z).filter(([nx,nz])=>{const b=clone(board),q=b[z][x];b[z][x]=null;if(q.t==='p'&&ep&&nx===ep.x&&nz===ep.z&&!b[nz][nx])b[z][nx]=null;b[nz][nx]=q;if(q.t==='k'&&Math.abs(nx-x)===2){const rx=nx===6?7:0,tx=nx===6?5:3;b[z][tx]=b[z][rx];b[z][rx]=null}return!isCheck(b,p.c)})}
function allMoves(c){const a=[];for(let z=0;z<8;z++)for(let x=0;x<8;x++)if(board[z][x]?.c===c)for(const[nx,nz]of legalMoves(x,z))a.push({x,z,nx,nz});return a}
function snapshot(){return{board:clone(board),turn,ep:ep?{...ep}:null,castling:JSON.parse(JSON.stringify(castling)),log:logEl.innerHTML}}
function restore(s){board=s.board;turn=s.turn;ep=s.ep;castling=s.castling;logEl.innerHTML=s.log;selected=null;legal=[];buildPieces();refresh()}
function notation(p,x,z,nx,nz,capture){return(p.t==='p'?'':p.t.toUpperCase())+(capture?'x':'')+String.fromCharCode(97+nx)+(8-nz)}
async function move(x,z,nx,nz,ai=false){if(busy)return;const p=board[z][x];if(!p)return;history.push(snapshot());let captured=board[nz][nx],capPos=captured?{x:nx,z:nz}:null;if(p.t==='p'&&ep&&nx===ep.x&&nz===ep.z&&!captured){captured=board[z][nx];capPos={x:nx,z};board[z][nx]=null}
 const oldEp=ep;ep=null;if(p.t==='p'&&Math.abs(nz-z)===2)ep={x,z:(z+nz)/2};
 if(p.t==='k'){castling[p.c].k=castling[p.c].q=false;if(Math.abs(nx-x)===2){const rx=nx===6?7:0,tx=nx===6?5:3;board[z][tx]=board[z][rx];board[z][rx]=null}}
 if(p.t==='r'){if(x===0)castling[p.c].q=false;if(x===7)castling[p.c].k=false}if(captured?.t==='r'){if(nx===0)castling[captured.c].q=false;if(nx===7)castling[captured.c].k=false}
 board[z][x]=null;board[nz][nx]=p;busy=true;if(captured)await battleFx(capPos.x,capPos.z,p,captured);busy=false;
 if(p.t==='p'&&(nz===0||nz===7)){if(ai){p.t='q'}else await promote(p)}
 const li=document.createElement('li');li.textContent=(turn==='w'?'White ':'Black ')+notation(p,x,z,nx,nz,!!captured);logEl.appendChild(li);logEl.scrollTop=logEl.scrollHeight;turn=opp(turn);selected=null;legal=[];buildPieces();refresh();if($('#mode').value==='ai'&&turn==='b'&&!gameOver())scheduleAI()}
function promote(p){return new Promise(resolve=>{const modal=$('#promotion'),box=$('#promotionChoices');box.innerHTML='';for(const t of['q','r','b','n']){const b=document.createElement('button');b.textContent=symbols[t];b.onclick=()=>{p.t=t;modal.classList.add('hidden');resolve()};box.appendChild(b)}modal.classList.remove('hidden')})}
function gameOver(){const moves=allMoves(turn);if(moves.length)return false;stateEl.textContent=isCheck(board,turn)?'Checkmate — '+(turn==='w'?'Black':'White')+' wins':'Stalemate — draw';return true}
function refresh(){turnEl.textContent=(turn==='w'?'White':'Black')+' to move';if(!gameOver())stateEl.textContent=isCheck(board,turn)?'CHECK':'Battle in progress';highlight()}
function highlight(){for(const o of boardGroup.children)if(o.userData.square){o.material.emissive.setHex(0);o.material.emissiveIntensity=.45;if(selected&&o.userData.x===selected.x&&o.userData.z===selected.z)o.material.emissive.setHex(0xfbbf24);const m=legal.find(a=>a[0]===o.userData.x&&a[1]===o.userData.z);if(m)o.material.emissive.setHex(board[m[1]][m[0]]?0xfb7185:0x2dd4bf)}}
function battleFx(x,z,a,d){beep(a.t==='q'?180:240,.12);const pos=new THREE.Vector3(x-3.5,.8,z-3.5),color=themes[theme].glow,parts=[];const count=theme==='brick'?22:theme==='cosmic'?14:10;for(let i=0;i<count;i++){const geo=theme==='brick'?new THREE.BoxGeometry(.13,.13,.13):new THREE.SphereGeometry(.055,6,5),m=mat(color,color),q=new THREE.Mesh(geo,m);q.position.copy(pos);q.userData.v=new THREE.Vector3((Math.random()-.5)*.13,Math.random()*.12+.05,(Math.random()-.5)*.13);fxGroup.add(q);parts.push(q)}return new Promise(res=>{let n=0;function tick(){n++;for(const q of parts){q.position.add(q.userData.v);q.userData.v.y-=.003;q.scale.multiplyScalar(.975)}if(n<42)requestAnimationFrame(tick);else{parts.forEach(q=>fxGroup.remove(q));res()}}tick()})}
function beep(freq=220,d=.08){if(!soundOn)return;const A=new (window.AudioContext||window.webkitAudioContext)(),o=A.createOscillator(),g=A.createGain();o.frequency.value=freq;o.type=theme==='cosmic'?'sine':'triangle';g.gain.setValueAtTime(.07,A.currentTime);g.gain.exponentialRampToValueAtTime(.001,A.currentTime+d);o.connect(g).connect(A.destination);o.start();o.stop(A.currentTime+d)}
function evaluate(){const v={p:100,n:320,b:330,r:500,q:900,k:20000};let s=0;for(const r of board)for(const p of r)if(p)s+=(p.c==='b'?1:-1)*v[p.t];return s}
function scheduleAI(){clearTimeout(aiTimer);aiTimer=setTimeout(aiMove,420)}
function aiMove(){if(turn!=='b'||busy)return;const moves=allMoves('b');if(!moves.length)return;let best=[],score=-1e9;for(const m of moves){const snap=snapshot(),capt=board[m.nz][m.nx];board[m.nz][m.nx]=board[m.z][m.x];board[m.z][m.x]=null;let s=evaluate()+(capt?35:0)+Math.random()*18;board=snap.board;if(s>score){score=s;best=[m]}else if(Math.abs(s-score)<1)best.push(m)}const m=best[Math.floor(Math.random()*best.length)];move(m.x,m.z,m.nx,m.nz,true)}
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();renderer.domElement.addEventListener('pointerup',e=>{if(busy||($('#mode').value==='ai'&&turn==='b'))return;const r=renderer.domElement.getBoundingClientRect();mouse.x=((e.clientX-r.left)/r.width)*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;ray.setFromCamera(mouse,camera);const hits=ray.intersectObjects([...pieceGroup.children,...boardGroup.children],true);if(!hits.length)return;let o=hits[0].object;while(o.parent&&!o.userData.piece&&!o.userData.square){if(o.userData.root){o=o.userData.root;break}o=o.parent}const d=o.userData;if(d.piece){const p=board[d.z][d.x];if(selected&&legal.some(m=>m[0]===d.x&&m[1]===d.z)){move(selected.x,selected.z,d.x,d.z);return}if(p?.c===turn){selected={x:d.x,z:d.z};legal=legalMoves(d.x,d.z);highlight()}}else if(d.square&&selected&&legal.some(m=>m[0]===d.x&&m[1]===d.z))move(selected.x,selected.z,d.x,d.z)});
function resize(){const w=sceneEl.clientWidth,h=sceneEl.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(sceneEl);
$('#newGame').onclick=()=>reset();$('#undo').onclick=()=>{clearTimeout(aiTimer);if(history.length){let s=history.pop();if($('#mode').value==='ai'&&s.turn==='b'&&history.length)s=history.pop();restore(s)}};$('#flip').onclick=()=>{camera.position.x*=-1;camera.position.z*=-1;controls.update()};$('#sound').onclick=e=>{soundOn=!soundOn;e.target.textContent='Sound: '+(soundOn?'On':'Off')};$('#theme').onchange=e=>{theme=e.target.value;buildBoard();buildPieces()};$('#menuBtn').onclick=e=>{const c=$('#controls');c.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',c.classList.contains('open'))};$('#mode').onchange=()=>reset();
buildBoard();reset();renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera)});
